import { Task } from "@/types";

export const generateMockTasks = (): Task[] => [
  {
    id: "task_1",
    title: "Understand user request",
    assignedTo: "gpt_orchestrator",
    status: "queued",
    progress: 0,
    dependsOn: [],
    outputPreview: "",
  },
  {
    id: "task_2",
    title: "Create multi-agent task plan",
    assignedTo: "gpt_orchestrator",
    status: "queued",
    progress: 0,
    dependsOn: ["task_1"],
    outputPreview: "",
  },
  {
    id: "task_3",
    title: "Analyze project structure",
    assignedTo: "kiro_dev_agent",
    status: "queued",
    progress: 0,
    dependsOn: ["task_2"],
    outputPreview: "",
  },
  {
    id: "task_4",
    title: "Review possible UI/UX issues",
    assignedTo: "claude_agent",
    status: "queued",
    progress: 0,
    dependsOn: ["task_2"],
    outputPreview: "",
  },
  {
    id: "task_5",
    title: "Summarize findings",
    assignedTo: "deepseek_agent",
    status: "queued",
    progress: 0,
    dependsOn: ["task_3", "task_4"],
    outputPreview: "",
  },
  {
    id: "task_6",
    title: "Execute safe local checks",
    assignedTo: "local_node_worker",
    status: "queued",
    progress: 0,
    dependsOn: ["task_2"],
    outputPreview: "",
  },
  {
    id: "task_7",
    title: "Build final response",
    assignedTo: "gpt_orchestrator",
    status: "queued",
    progress: 0,
    dependsOn: ["task_5", "task_6"],
    outputPreview: "",
  },
];
