import { AIProvider } from "@/types";

export const mockAgents: AIProvider[] = [
  {
    id: "gpt_orchestrator",
    name: "GPT Orchestrator",
    role: "Main Controller",
    model: "GPT / OpenAI-Compatible",
    status: "online",
    capabilities: ["planning", "routing", "final answer"],
    lastActive: new Date().toISOString(),
  },
  {
    id: "deepseek_agent",
    name: "DeepSeek V4 Flash",
    role: "Fast Analyst",
    model: "OpenRouter - deepseek/deepseek-v4-flash:free",
    status: "online",
    capabilities: ["fast summary", "task breakdown", "low-cost reasoning", "trend analysis"],
    lastActive: new Date().toISOString(),
  },
  {
    id: "hermes_agent",
    name: "Hermes Agent",
    role: "General Reasoning",
    model: "Hermes / OpenRouter-Compatible",
    status: "online",
    capabilities: ["general reasoning", "instruction following", "tool planning", "drafting"],
    lastActive: new Date().toISOString(),
  },
  {
    id: "nemotron_agent",
    name: "Nemotron Agent",
    role: "NVIDIA Reasoning",
    model: "NVIDIA Nemotron / OpenRouter-Compatible",
    status: "online",
    capabilities: ["reasoning", "summarization", "agent planning", "analysis"],
    lastActive: new Date().toISOString(),
  },
  {
    id: "claude_agent",
    name: "Claude Agent",
    role: "Deep Reasoning",
    model: "Claude",
    status: "standby",
    capabilities: ["code review", "risk analysis", "complex reasoning"],
    lastActive: new Date().toISOString(),
  },
  {
    id: "kiro_dev_agent",
    name: "Kiro Dev Agent",
    role: "Codebase Worker",
    model: "Kiro",
    status: "standby",
    capabilities: ["edit code", "refactor", "inspect project"],
    lastActive: new Date().toISOString(),
  },
  {
    id: "local_node_worker",
    name: "Local Node Worker",
    role: "Executor",
    model: "Node.js Worker",
    status: "online",
    capabilities: ["run safe tools", "build", "read logs"],
    lastActive: new Date().toISOString(),
  },
  {
    id: "artifact_renderer",
    name: "Artifact Renderer",
    role: "Output Renderer",
    model: "internal",
    status: "online",
    capabilities: ["chart", "report", "code preview"],
    lastActive: new Date().toISOString(),
  },
];
